export function Data(scene) {
    //liste de tout les minerais et quantiter
    scene.dataMinerais = {
        rubis: { presentation: "rubis", brut: { quantiter: 0, image: "" }, soigne: { quantiter: 0, image: "" }, pur: { quantiter: 0, image: "" }, raffine: { quantiter: 0, image: "" }, elegant: { quantiter: 0, image: "" }, brillant: { quantiter: 0, image: "" }, carre: { quantiter: 0, image: "" }, grave: { quantiter: 0, image: "" }, ovale: { quantiter: 0, image: "" }, parfait: { quantiter: 0, image: "" } },
        saphirs: { presentation: "saphirs", brut: { quantiter: 0, image: "" }, soigne: { quantiter: 0, image: "" }, pur: { quantiter: 0, image: "" }, raffine: { quantiter: 0, image: "" }, elegant: { quantiter: 0, image: "" }, brillant: { quantiter: 0, image: "" }, carre: { quantiter: 0, image: "" }, grave: { quantiter: 0, image: "" }, ovale: { quantiter: 0, image: "" }, parfait: { quantiter: 0, image: "" } },
        topazes: { presentation: "topazes", brut: { quantiter: 0, image: "" }, soigne: { quantiter: 0, image: "" }, pur: { quantiter: 0, image: "" }, raffine: { quantiter: 0, image: "" }, elegant: { quantiter: 0, image: "" }, brillant: { quantiter: 0, image: "" }, carre: { quantiter: 0, image: "" }, grave: { quantiter: 0, image: "" }, ovale: { quantiter: 0, image: "" }, parfait: { quantiter: 0, image: "" } },
        emeraudes: { presentation: "emeraudes", brut: { quantiter: 0, image: "" }, soigne: { quantiter: 0, image: "" }, pur: { quantiter: 0, image: "" }, raffine: { quantiter: 0, image: "" }, elegant: { quantiter: 0, image: "" }, brillant: { quantiter: 0, image: "" }, carre: { quantiter: 0, image: "" }, grave: { quantiter: 0, image: "" }, ovale: { quantiter: 0, image: "" }, parfait: { quantiter: 0, image: "" } },
        onyx: { presentation: "onyx", brut: { quantiter: 0, image: "" }, soigne: { quantiter: 0, image: "" }, pur: { quantiter: 0, image: "" }, raffine: { quantiter: 0, image: "" }, elegant: { quantiter: 0, image: "" }, brillant: { quantiter: 0, image: "" }, carre: { quantiter: 0, image: "" }, grave: { quantiter: 0, image: "" }, ovale: { quantiter: 0, image: "" }, parfait: { quantiter: 0, image: "" } },
        diamants: { presentation: "diamants", brut: { quantiter: 0, image: "" }, soigne: { quantiter: 0, image: "" }, pur: { quantiter: 0, image: "" }, raffine: { quantiter: 0, image: "" }, elegant: { quantiter: 0, image: "" }, brillant: { quantiter: 0, image: "" }, carre: { quantiter: 0, image: "" }, grave: { quantiter: 0, image: "" }, ovale: { quantiter: 0, image: "" }, parfait: { quantiter: 0, image: "" } }
    }
}